<a href="https://colab.research.google.com/github/BarbaraLipinska24/Data_Science_Python-exercises/blob/main/NumPy/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Ćwiczenie 21
Wygeneruj następującą tablicę numpy.



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


Następnie zapisz tablicę do pliku binarnego o nazwie 'array.npy', załaduj ten plik z powrotem do innej zmiennej i wydrukuj jej zawartość do konsol

In [12]:
array=np.arange(12)
array=np.resize(array,(3,4))
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
