<a href="https://colab.research.google.com/github/BarbaraLipinska24/Data_Science_Python-exercises/blob/main/NumPy/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1. Sprawdź czy poniższe elementy zwracają wartośc logiczną True

In [2]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])


In [3]:
print('A:',np.all(A))
print('B:',np.all(B))
print('C:',np.all(C))
print('D:',np.all(D))

A: True
B: False
C: False
D: True


2. Sprawdź, czy wszystkie elementy z tablic A,B,C zwracają wartośc logiczną True wzdłuż osi o indeksie 1

In [4]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

In [6]:
print('A:',np.all(A,axis=1))
print('B:',np.all(B,axis=1))
print('C:',np.all(C,axis=1))

#lub

for name, array in zip(list('ABC'),[A,B,C]):
    print(f'{name}:{np.all(array,axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]
A:[ True  True]
B:[ True False]
C:[False  True]


3. Sprawdź, czy którykolwiek element tablic A, B, C i D zwraca wartość logiczną True.

In [7]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [8]:
for name,array in zip(list('ABCD'),[A,B,C,D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


4. Sprawdź, czy którykolwiek element tablic A, B, C i D zwraca wartość logiczną True wzdłuż osi z indeksem 0.

In [9]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [10]:
for name, array in zip(list('ABCD'),[A,B,C,D]):
    print(f'{name}:{np.any(array,axis=0)}')

A:[False False False]
B:[False  True False]
C:[ True False False]
D:[ True False]


5. Sprawdź macierz A pod kątem brakujących danych (np.nan). Wydrukuj wynik na konsoli.

In [12]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

In [13]:
np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

6. Sprawdź, czy następujące tablice A i B są równe pod względem elementów z określonym poziomem tolerancji. Użyj funkcji np.allclose() z domyślnymi parametrami. Wydrukuj wynik do konsoli.

In [14]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

In [15]:
print(np.allclose(A,B))

True


7. Sprawdź, czy poniższe tablice A i B są równe pod względem elementów. Użyj operatora porównania ==. Wydrukuj wynik do konsoli.

In [16]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

In [18]:
print(A==B)

[False False  True]


8. Sprawdź, które elementy z tablicy A mają wyższe wartości niż tablica B. Wydrukuj wynik do konsoli.

In [19]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

In [21]:
print(A>B)

[ True False False False]


9. Utwórz tablicę numpy o kształcie 4x4 wypełnioną zerami. Ustaw typ danych na int. Wydrukuj wynik do konsoli.

In [31]:
print(np.zeros(shape=(4,4),dtype=int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


10. Utwórz tablicę numpy o kształcie 10x10 wypełnioną liczbą 255. Ustaw typ danych na float.

In [36]:
print(np.full(shape=(10,10), fill_value=255, dtype=float))

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]
